schemaVersion: 2.3.0
components:
  - name: nginx
    container:
      image: node:18-alpine
      endpoints:
        - name: http-3000
          targetPort: 3000
commands:
  - id: update
    exec:
      commandLine: yum update
      component: nginx
      workingDir: .
      group:
        isDefault: true
        kind: build
  - id: run
    exec:
      commandLine: echo "Holi"
      component: nginx
      workingDir: .
      group:
        isDefault: true
        kind: run